services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    env_file:
      - path: ./back/.env
    ports:
      - "3001:3001"
    labels:
      com.orga-planning.service: "Nest Backend"
      com.orga-planning.description: "Backend using framework Nest"
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - "3000:3000"
    env_file:
      - path: ./front/.env
        required: false
    labels:
      com.orga-planning.service: "Next Frontend"
      com.orga-planning.description: "Front using framework Next"