import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Metadata } from 'next';
import { Inter, Roboto_Serif } from 'next/font/google';
import { Suspense } from 'react';
import { Toaster } from 'sonner';
import HeaderBar from '~/module/header/headerBar.component';
import Modals from '~/module/modals/modals.component';
import './globals.css';
import { ConfigProvider } from 'antd';
import frFR from 'antd/es/locale/fr_FR';

const inter = Inter({ subsets: ['latin'] });
const roboto = Roboto_Serif({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Ma présence',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <AntdRegistry>
            <ConfigProvider
                locale={frFR}
                theme={{
                    token: {
                        colorPrimary: '#47b5b9'
                    }
                }}
            >
                <html lang="en" suppressHydrationWarning>
                    <body className={inter.className}>
                        <div className="h-screen">
                            <div className=" relative w-screen z-50">
                                <HeaderBar />
                                <Suspense fallback={<div>Loading...</div>}>
                                    <Modals />
                                </Suspense>
                            </div>
                            <div className="relative md:top-[100px] min-h-[80%] flex justify-center pt-5 mb-10 z-30">
                                {children}
                            </div>
                        </div>
                        <Toaster position="bottom-right" richColors />
                    </body>
                </html>
            </ConfigProvider>
        </AntdRegistry>
    );
}
